-name: install nginx and run nginx
hosts: web
become: yes #-b becoms adhoc command getting root access
tasks:
  name: Install nginx
  ansible.builtin.dnf;
    name: nginx
    state: latest
  name: Start nginx
  ansible.builtin.service;
    name: mginx
    state: started
    enabled: yes
  
