- name: variables from files
  hosts: localhosts
  vars_files:
  - vars.yaml
  tasks:
  - name: print override info
    ansible.builtin.debug:
    msg: "Hi, learining {{Course}}, {{Trainer}}, {{Duration}}"